"""empty message

Revision ID: 6e1cbc828430
Revises: a0e47b8e1d88
Create Date: 2020-10-12 22:08:02.569772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e1cbc828430'
down_revision = 'a0e47b8e1d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_cat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.Column('c_eat', sa.String(length=32), nullable=True),
    sa.Column('c_age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animal_cat_id'), 'animal_cat', ['id'], unique=False)
    op.create_table('animal_dog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.Column('d_eat', sa.String(length=32), nullable=True),
    sa.Column('d_age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animal_dog_id'), 'animal_dog', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_animal_dog_id'), table_name='animal_dog')
    op.drop_table('animal_dog')
    op.drop_index(op.f('ix_animal_cat_id'), table_name='animal_cat')
    op.drop_table('animal_cat')
    # ### end Alembic commands ###
