"""empty message

Revision ID: a0e47b8e1d88
Revises: 
Create Date: 2020-10-11 15:32:49.695991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e47b8e1d88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subname', sa.String(length=16), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('record',
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('daytype', sa.String(), nullable=True),
    sa.Column('starttime', sa.DateTime(), nullable=True),
    sa.Column('endtime', sa.DateTime(), nullable=True),
    sa.Column('applytime', sa.DateTime(), nullable=True),
    sa.Column('recordtime', sa.DateTime(), nullable=True),
    sa.Column('ipaddr', sa.String(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('rid')
    )
    op.create_index(op.f('ix_record_uid'), 'record', ['uid'], unique=False)
    op.create_table('recordtype',
    sa.Column('rid', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('rid')
    )
    op.create_index(op.f('ix_recordtype_rid'), 'recordtype', ['rid'], unique=False)
    op.create_table('user',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('yearsofwork', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_user_uid'), 'user', ['uid'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=16), nullable=True),
    sa.Column('password', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix_user_uid'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_recordtype_rid'), table_name='recordtype')
    op.drop_table('recordtype')
    op.drop_index(op.f('ix_record_uid'), table_name='record')
    op.drop_table('record')
    op.drop_table('member')
    # ### end Alembic commands ###
