---
- hosts: local
  remote_user: root
  gather_facts: no
  tasks:
  - debug:
      msg: "{{ item }}"
    with_file:  #可以通过"with_file"关键字获取到ansible主机中的文件内容
    - /tmp/demo1.txt  #ansbile主机上的文件
    - /tmp/demo2.txt
